language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t suhaasnandeesh/docker-react-udemy -f Dockerfile.dev .

script:
  - docker run suhaasnandeesh/docker-react-udemy npm run test -- --coverage